api:
  server:
    tls:
      cert_file: /tmp/openssl/root/ca/intermediate/certs/server.cert.pem #Server side cert
      key_file: /tmp/openssl/root/ca/intermediate/private/server.key.pem #Server side key
      ca_cert_path: /tmp/openssl/root/ca/intermediate/certs/ca-chain.cert.pem #CA used to verify the client certs
      bouncers_allowed_ou:
        - bouncer-ou
      agents_allowed_ou:
        - agent-ou
