#!/usr/bin/env bash

## Description: Run PHPCBF for some folder
## Usage: phpcbf bin_source folder
## Example: "ddev phpcbf ./my-own-modules/my-module/vendor/bin/phpcbf my-own-modules/my-module --ignore="*/node_modules/*""

PHPCBF_SOURCE=${1:-./vendor/bin/phpcbf}
MODULE_SOURCE=${2:-my-own-modules/my-module}

/usr/bin/php $PHPCBF_SOURCE $MODULE_SOURCE
