#!/usr/bin/env bash

## Description: Run PSALM for some folder
## Usage: psalm psalm_source command
## Example: "ddev psalm ./my-own-modules/my-module/ --init"


PSALM_SOURCE=${1:-./}
CONFIG_SOURCE=${2:-}

/usr/bin/php $PSALM_SOURCE/vendor/bin/psalm  --root=$CONFIG_SOURCE  --show-info=true
